apiVersion: batch/v1
kind: Job
metadata:
  name: argocd-add-cluster-job
spec:
  template:
    spec:
      containers:
        - name: argocd
          image: quay.io/thason/argo-oc-tool:v4
          command: ["/bin/sh", "-c"]
          args:
            - wget https://raw.githubusercontent.com/tal-hason/argocdaas-automation/main/docker/clusters
            - add-cluster.sh
          envFrom:
            - configMapRef:
                name: argocd-env-configmap
  backoffLimit: 0
