kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-env-configmap
data:
  ARGOCD_PASSWORD: <<ArgoCD Admin Password>>
  ARGOCD_SERVER: openshift-gitops-server
  ARGOCD_USERNAME: admin
  CLUSTER_CA_CONFIGMAP: kube-root-ca.crt
  CLUSTER_TOKEN: <<ServiceAccount Token>>
  CLUSTER_API_URL: https://api.crc.testing:6443